### PR TITLE
fix el5-asm-compat.patch

### PR DESCRIPTION
**Pull request by jhoblitt**
Bad migration from conda-lsst.  Format was a patch-in-patch... creating
the patch is not as useful as applying it.

### CODE REVIEW

**Comment by timj** [comment]
This PR confused me completely. Why does it look like it's trying to update the binary again?

**Comment by jhoblitt** [comment]
Uh... that's a good question.  Something weird seems to have happened with the history.

**Comment by jhoblitt** [comment]
I rebased on the current master and the shas for the commits from #3 were wrong -- I have no idea how the could have happened.  I have no idea why github is listing so many commits in this PR -- I have checked the shas.

**Comment by jhoblitt** [comment]
I'm going to close this PR and reopen it.

**Pull request closed without merging**
